name = "YaoWave"
uuid = "03de0c60-7835-501c-93ad-24020a64001e"
authors = ["GiggleLiu <cacate0129@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
